import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ReduxProvider from "@/components/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className={"flex justify-center py-2"}>
          hey from layout, <Link href={"/"}>Go to main page </Link>
        </h1>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
